// Regenerates the frontend MoveChain ABI from the compiled Hardhat artifact.
// Keeps frontend/src/abi/moveChain.ts in sync with contracts/MoveChain.sol.
//
// Usage: node scripts/gen-abi.mjs   (run after `hardhat compile`)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifactPath = join(root, "artifacts/contracts/MoveChain.sol/MoveChain.json");
const outPath = join(root, "frontend/src/abi/moveChain.ts");

let artifact;
try {
  artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
} catch {
  throw new Error(
    `Artifact not found at ${artifactPath}. Run \`npm run compile\` first.`,
  );
}

const header =
  "// Auto-generated by scripts/gen-abi.mjs from the compiled MoveChain artifact.\n" +
  "// Do not edit by hand. Run `npm run gen:abi` (after `npm run compile`) to refresh.\n";
const body = `export const moveChainAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

writeFileSync(outPath, header + body);
console.log(`Wrote ${outPath} with ${artifact.abi.length} ABI entries`);
